export var january: any ;
export var february: any ;
export var march: any ;
export var april: any ;
export var may: any ;
export var june: any ;
export var july: any ;
export var august: any ;
export var september: any ;
export var october: any ;
export var november: any ;
export var december: any ;
export var sunday: any ;
export var monday: any ;
export var tuesday: any ;
export var wednesday: any ;
export var thursday: any ;
export var friday: any ;
export var saturday: any ;
export var int_of_month: (month : any) => any ;
export var int_of_day: (day : any) => any ;
export var dayOfMillis: any ;
export var date_of_int: any ;
export var date_of_float: any ;
export var int_of_date: any ;
export var beginningOfMonth: (t : any) => any ;
export var beginningOfNextMonth: (t : any) => any ;
export var make: (year : any, month : any, day : any) => any ;
export var Infix: any ;
export var now: (param : any) => any ;
export var dayToString: (day : any) => any ;
export var dateToString: (t : any) => any ;
export var monthToString: (month : any) => any ;

